version: "3.8"



services:
  paperless:
    container_name: paperless
    image: lscr.io/linuxserver/paperless-ng
    restart: always
    environment:
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "TZ=${TZ}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.entrypoints=websecure"
      - "traefik.http.routers.paperless.rule=Host(`${PAPERLESS_DOMAIN}`)"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.routers.paperless.tls.certresolver=${TLS_RESOLVER}"
    volumes:
      - "config:/config"
      - "data:/data"
	networks:
      - "proxy"



volumes:
  data:
  config:


networks:
  proxy:
  	name: traefik_default